set relativenumber
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set hlsearch
colorscheme catppuccin_mocha " catppuccin-latte, catppuccin-frappe, catppuccin-macchiato, catppuccin-mocha
set laststatus=2
let g:lightline = {'colorscheme': 'catppuccin_mocha'}
set noshowmode
let mapleader = " " 
nnoremap <silent> <leader>e :if &filetype == 'netrw' <bar> q <bar> else <bar> Vexplore <bar> endif<CR>

"if has('nvim')
"	lua << EOF
"		-- Telescope Setup
"    require "telescope".setup{
"      pickers = {
"        colorscheme = {
"          enable_preview = true
"        }
"      }
"    }
"		local builtin = require('telescope.builtin')
"		vim.keymap.set('n', '<leader>ff', function() builtin.find_files({ hidden = true }) end, { desc = 'Telescope find files' })
"		vim.keymap.set('n', '<leader>fg', function() builtin.live_grep({ hidden = true }) end, { desc = 'Telescope live grep' })
"		vim.keymap.set('n', '<leader>fb', function() builtin.buffers({ hidden = true }) end, { desc = 'Telescope buffers' })
"		vim.keymap.set('n', '<leader>fh', function() builtin.help_tags({ hidden = true }) end, { desc = 'Telescope help tags' })
"		vim.keymap.set('n', '<leader>cs', builtin.colorscheme, { desc = 'Colorschemes' })
"		-- Treesitter Setup
"		require('nvim-treesitter.configs').setup({
"		  ensure_installed = { "lua", "python", "latex" },
"		  highlight = { enable = true},
"		  indent = {enable = true},
"		})
"EOF
"else
"endif
